name: github pages

on:
  push:
    branches:
      - master

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'

    - name: Build and Deploy
      run: |
        git config --global user.email sean@arrowburn.co.nz
        git config --global user.name "Sean Magin"
        npm i
        npm run deploy


